name: EDS
channels:
  - conda-forge
dependencies:
  - python=3.8
  - r-base>=4.0
  - autopep8
  - cartopy
  - cenpy
  - climata
  - contextily
  - descartes
  - earthpy>=0.9.2
  - elevation
  - folium
  - branca=0.3.1
  - geocoder
  - geojson
  - geopandas
  - geopy
  - hydrofunctions
  - mapboxgl
  - mapclassify
  - nano
  - nbclean
  - nbconvert=5.6.1
  - nc-time-axis
  - netcdf4
  - nltk
  - papermill
  - proj>=7
  - pyproj>=3.0
  - pyqt
  - pysal
  - r-codetools
  - r-rcolorbrewer
  - r-cowplot
  - r-cyphr
  - r-curl
  - r-devtools
  - r-dplyr
  - r-dygraphs
  - r-ff
  - r-ggmap
  - r-ggplot2
  - r-ggsn
  - r-gridextra
  - r-knitr
  - r-lemon
  - r-magick
  - r-mapdata
  - r-maps
  - r-maptools
  - r-microbenchmark
  - r-plotly
  - r-r.utils
  - r-raster
  - r-rastervis
  - r-rgdal
  - r-rgeos
  - r-rjsonio
  - r-rmarkdown
  - r-rsaga
  - r-rtweet
  - r-sf
  - r-stringr
  - r-widyr
  - r-tm
  - r-igraph
  - r-leaflet
  - r-lubridate
  - r-rcurl
  - r-ggraph
  - r-ggthemes
  - r-gganimate
  - r-readr
  - r-webshot
  - r-zoo
  - rasterio
  - rasterstats
  - regionmask
  - richdem
  - rioxarray
  - scikit-image
  - scikit-learn
  - shapely
  - textblob
  - traitlets=4.3.3
  - tweepy
  - xarray
