name: build-image

on:
  push:
    branches: *

jobs:
  multi-builders:
    runs-on: ubuntu-latest
    steps:
      -
        uses: docker/setup-buildx-action@v1
        id: builder1
      -
        name: Builder 1 name
        run: echo ${{ steps.builder1.outputs.name }}
